"""Centralized user-facing strings for island UI modules."""

from __future__ import annotations

APP_TITLE = "设置"

WINDOW_SETTINGS = "设置"
WINDOW_MINIMIZE = "最小化"
WINDOW_MAXIMIZE = "最大化"
WINDOW_RESTORE = "还原"
WINDOW_CLOSE = "关闭"

ROUTE_RENAME = "重命名"
ROUTE_DELETE = "删除"
ROUTE_RENAME_PLACEHOLDER = "输入路线名称..."
ROUTE_RENAME_CONFIRM = "确认重命名"
ROUTE_RENAME_CANCEL = "取消重命名"
ROUTE_ADD_CATEGORY = "新增类别"
ROUTE_ADD_CATEGORY_PLACEHOLDER = "输入类别名称..."
ROUTE_ADD_CATEGORY_CONFIRM = "确认创建类别"
ROUTE_ADD_CATEGORY_CANCEL = "取消新增类别"
ROUTE_LIST_TITLE = "路线列表"
ROUTE_LIST_REFRESH = "刷新列表"
ROUTE_LIST_REFRESH_TOOLTIP = "重新读取 routes 文件夹下的所有路线"
ROUTE_ADD_CATEGORY_TOOLTIP = "新增一个路线类别文件夹"
ROUTE_TRACKED_TITLE = "当前追踪路线"
ROUTE_RECENT_TITLE = "最近常用"
ROUTE_EMPTY_RECENT = "暂无最近常用路线"
ROUTE_EMPTY_TRACKED = "暂无已选择路线"
ROUTE_DELETE_TITLE = "删除路线"
ROUTE_DELETE_MESSAGE = "确认删除路线“{name}”吗？"
ROUTE_DELETE_CONFIRM = "删除"
ROUTE_DELETE_CANCEL = "取消"
ROUTE_RENAME_EMPTY = "路线名称不能为空"
ROUTE_RENAME_INVALID = "名称无效或已存在"
ROUTE_CATEGORY_EMPTY = "类别名称不能为空"
ROUTE_CATEGORY_INVALID = "名称不能包含 / 或 \\"

HEADER_RELOCATE = "重定位"
HEADER_RESET_VIEW = "重置视图"
HEADER_HIDE_SIDEBAR = "隐藏侧边栏"
HEADER_SHOW_SIDEBAR = "展开侧边栏"
HEADER_START_NAV = "开始导航"
HEADER_TERMINATE = "终止导航"
HEADER_LOCK = "锁定"
HEADER_UNLOCK = "解锁"
HEADER_UNLOCK_HINT = "快捷键 Alt+~ 解锁"

MAP_HINT = "滚轮缩放，左键拖动，双击选点"
SEARCH_PLACEHOLDER = "搜索路线..."

STATE_LOCKED = "定位稳定"
STATE_INERTIAL = "定位暂时不稳定，沿用上一帧位置。"
STATE_SEARCHING = "正在搜索目标，请稍候…"
STATE_PAUSED = "暂停定位"
ALERT_LOST = "目标丢失，正在尝试重新定位。"

MINI_ICON_RESTORE = "还原窗口"
MINI_ICON_CLOSE = "关闭程序"

SETTINGS_SAVED = "设置已应用"
MINIMAP_UPDATED = "小地图区域已更新"
SETTINGS_SAVE_FAILED = "写入 config.json 失败：{error}"
SETTINGS_INVALID_INPUT = "字段 {label} 的值“{value}”无法解析为 {type_name}。"
SETTINGS_INVALID_MINIMAP = "小地图 {key} 的值“{value}”不是有效整数。"
SETTINGS_RESTART_REQUIRED_TITLE = "需要重启"
SETTINGS_RESTART_REQUIRED_MESSAGE = "已保存，但以下参数需要重启应用后才会生效：\n\n  路 {fields}"

MINIMAP_PREVIEW_TITLE = "确认小地图截取区域"
MINIMAP_RETAKE = "重新截取"
MINIMAP_CONFIRM = "确定"
MINIMAP_SET = "设置小地图"
MINIMAP_OVERLAY_TOP = "左键拖动 | 滚轮缩放"
MINIMAP_OVERLAY_BOTTOM = "按 回车/双击 确认截图"
