"""Centralized user-facing strings for island UI modules."""

from __future__ import annotations

APP_TITLE = "设置"

WINDOW_SETTINGS = "设置"
WINDOW_MINIMIZE = "最小化"
WINDOW_MAXIMIZE = "最大化"
WINDOW_RESTORE = "还原"
WINDOW_CLOSE = "关闭"

ROUTE_RENAME = "重命名"
ROUTE_DELETE = "删除"
ROUTE_NOTES = "查看/修改说明"
ROUTE_OPEN_FILE_LOCATION = "打开文件位置"
ROUTE_RENAME_PLACEHOLDER = "输入路线名称..."
ROUTE_RENAME_CONFIRM = "确认重命名"
ROUTE_RENAME_CANCEL = "取消重命名"
ROUTE_ADD_CATEGORY = "新增类别"
ROUTE_ADD_CATEGORY_PLACEHOLDER = "输入类别名称..."
ROUTE_ADD_CATEGORY_CONFIRM = "确认创建类别"
ROUTE_ADD_CATEGORY_CANCEL = "取消新增类别"
ROUTE_LIST_TITLE = "路线列表"
ROUTE_LIST_REFRESH = "刷新列表"
ROUTE_LIST_REFRESH_TOOLTIP = "重新读取 routes 文件夹下的所有路径"
ROUTE_ADD_CATEGORY_TOOLTIP = "新增一个路线类别文件夹"
ROUTE_TRACKED_TITLE = "当前追踪路线"
ROUTE_RECENT_TITLE = "最近常用"
ROUTE_EMPTY_RECENT = "暂无最近常用路线"
ROUTE_EMPTY_TRACKED = "暂无已选择路线"
ROUTE_DELETE_TITLE = "删除路线"
ROUTE_DELETE_MESSAGE = "确认删除路线“{name}”吗？"
ROUTE_DELETE_CONFIRM = "删除"
ROUTE_DELETE_CANCEL = "取消"
ROUTE_NOTES_TITLE = "路线说明"
ROUTE_NOTES_PLACEHOLDER = "可以为这条路线补充说明、提示或注意事项..."
ROUTE_NOTES_CONFIRM = "确认修改"
ROUTE_NOTES_CANCEL = "取消修改"
ROUTE_NOTES_SAVED = "已保存路线“{name}”的说明"
ROUTE_NOTES_SAVE_FAILED = "保存路线“{name}”的说明失败"
ROUTE_OPEN_FILE_LOCATION_FAILED = "无法打开路线“{name}”的文件位置"
ROUTE_RENAME_EMPTY = "路线名称不能为空"
ROUTE_RENAME_INVALID = "名称无效或已存在"
ROUTE_CATEGORY_EMPTY = "类别名称不能为空"
ROUTE_CATEGORY_INVALID = "名称不能包含 / 或 \\"
ROUTE_CATEGORY_RENAME = "重命名分类"
ROUTE_CATEGORY_DELETE = "删除分类"
ROUTE_CATEGORY_OPEN_FILE_LOCATION = "打开分类文件位置"
ROUTE_CATEGORY_RENAME_TITLE = "重命名分类"
ROUTE_CATEGORY_RENAME_PLACEHOLDER = "输入分类名称..."
ROUTE_CATEGORY_RENAME_CONFIRM = "确认重命名"
ROUTE_CATEGORY_RENAME_CANCEL = "取消重命名"
ROUTE_CATEGORY_DELETE_TITLE = "删除分类"
ROUTE_CATEGORY_DELETE_MESSAGE = "确认删除分类“{name}”吗？\n\n该分类下的所有路线和文件都将被删除。"
ROUTE_CATEGORY_DELETE_CONFIRM = "删除"
ROUTE_CATEGORY_DELETE_CANCEL = "取消"
ROUTE_CATEGORY_RENAME_EMPTY = "分类名称不能为空"
ROUTE_CATEGORY_RENAME_INVALID = "分类名称无效或已存在"
ROUTE_CATEGORY_OPEN_FILE_LOCATION_FAILED = "无法打开分类“{name}”的文件位置"

HEADER_RELOCATE = "重定位"
HEADER_RESET_VIEW = "重置视图"
HEADER_HIDE_SIDEBAR = "隐藏侧边栏"
HEADER_SHOW_SIDEBAR = "展开侧边栏"
HEADER_START_NAV = "开始导航"
HEADER_TERMINATE = "终止导航"
HEADER_LOCK = "锁定"
HEADER_UNLOCK = "解锁"
HEADER_UNLOCK_HINT = "快捷键 Alt+~ 解锁"

MAP_HINT = "滚轮缩放，左键拖动，双击选点"

INSERT_POINT_DIALOG_TITLE = "添加节点到路线"
INSERT_POINT_COORD_FMT = "坐标：X = {x}，Y = {y}"
INSERT_POINT_ROUTES_LABEL = "目标路线（勾选要插入的）："
INSERT_POINT_SUGGEST_FMT = "建议第 {pos} 位（共 {total} 位）"
INSERT_POINT_POSITION_LABEL = "插入位置："
INSERT_POINT_CONFIRM = "确认插入"
INSERT_POINT_CANCEL = "取消"
INSERT_POINT_NO_SELECTION = "请至少勾选一条路线"
INSERT_POINT_MULTI_WARN_TITLE = "多路线插入提示"
INSERT_POINT_MULTI_WARN_BODY = "多条路线同时插入将统一使用算法推荐位置，可能会打乱您在高低差地形上精心排列的节点顺序，不推荐此操作。确定要继续吗？"
INSERT_POINT_SUCCESS_FMT = "已向 {count} 条路线插入节点"
INSERT_POINT_PARTIAL_FMT = "已插入 {ok} 条，失败 {fail} 条"
INSERT_POINT_FAIL_TITLE = "插入失败"
INSERT_POINT_FAIL_BODY = "未能写入任何路线文件，请查看日志。"
INSERT_POINT_EMPTY_TITLE = "无追踪路线"
INSERT_POINT_EMPTY_BODY = "请先在侧边栏勾选至少一条路线后再添加节点。"

DELETE_POINT_MENU_LABEL = "删除此节点"
MARK_POINT_VISITED_MENU_LABEL = "标记已到"
MARK_POINT_UNVISITED_MENU_LABEL = "标记未到"
DELETE_POINT_TITLE = "删除节点"
DELETE_POINT_SINGLE_BODY_FMT = "确认删除路线“{name}”的第 {pos} 个节点吗？"
DELETE_POINT_MULTI_SINGLE_ROUTE_FMT = "确认删除路线“{name}”的 {count} 个节点吗？"
DELETE_POINT_MULTI_ROUTES_FMT = "确认删除 {routes} 条路线上共 {count} 个节点吗？"
DELETE_POINT_CONFIRM = "删除"
DELETE_POINT_CANCEL = "取消"
DELETE_POINT_SUCCESS_FMT = "已删除 {count} 个节点"
DELETE_POINT_PARTIAL_FMT = "已删除 {ok} 个，失败 {fail} 个"
DELETE_POINT_FAIL_TITLE = "删除失败"
DELETE_POINT_FAIL_BODY = "未能从任何路线中删除节点，请查看日志。"
SEARCH_PLACEHOLDER = "搜索路线..."

STATE_LOCKED = "定位稳定"
STATE_INERTIAL = "定位暂时不稳定，沿用上一帧位置。"
STATE_SEARCHING = "正在搜索目标，请稍候..."
STATE_PAUSED = "暂停定位"
ALERT_LOST = "目标丢失，正在尝试重新定位。"

MINI_ICON_RESTORE = "还原窗口"
MINI_ICON_CLOSE = "关闭程序"

SETTINGS_SAVED = "设置已应用"
MINIMAP_UPDATED = "小地图区域已更新"
SETTINGS_SAVE_FAILED = "写入 config.json 失败：{error}"
SETTINGS_INVALID_INPUT = "字段 {label} 的值“{value}”无法解析为 {type_name}。"
SETTINGS_INVALID_MINIMAP = "小地图 {key} 的值“{value}”不是有效整数。"
SETTINGS_RESTART_REQUIRED_TITLE = "需要重启"
SETTINGS_RESTART_REQUIRED_MESSAGE = "已保存，但以下参数需要重启应用后才会生效：\n\n  {fields}"

MINIMAP_PREVIEW_TITLE = "确认小地图截取区域"
MINIMAP_RETAKE = "重新截取"
MINIMAP_CONFIRM = "确定"
MINIMAP_SET = "设置小地图"
MINIMAP_OVERLAY_TOP = "左键拖动 | 滚轮缩放"
MINIMAP_OVERLAY_BOTTOM = "按 回车/双击 确认截图"
