"""Shared design tokens for island UI modules."""

from __future__ import annotations

from . import theme

COLLAPSED_W = theme.COLLAPSED_W
COLLAPSED_H = theme.COLLAPSED_H
EXPANDED_W = theme.EXPANDED_W
EXPANDED_H = theme.EXPANDED_H
TOP_MARGIN = theme.TOP_MARGIN
ANIMATION_MS = theme.ANIMATION_MS
RECENT_ROUTES_MAX_HEIGHT = theme.RECENT_ROUTES_MAX_HEIGHT
TRACKED_ROUTES_MAX_HEIGHT = theme.TRACKED_ROUTES_MAX_HEIGHT
ROUTES_LIST_MIN_HEIGHT = theme.ROUTES_LIST_MIN_HEIGHT
SIDEBAR_RAIL_WIDTH = theme.SIDEBAR_RAIL_WIDTH
MAXIMIZED_SIDEBAR_WIDTH = theme.MAXIMIZED_SIDEBAR_WIDTH
WINDOW_MIN_W = theme.WINDOW_MIN_W
WINDOW_MIN_H = theme.WINDOW_MIN_H
TRACKING_WINDOW_MIN_H = theme.TRACKING_WINDOW_MIN_H
SIDEBAR_MIN_EXPANDED_W = theme.SIDEBAR_MIN_EXPANDED_W
SIDEBAR_MIN_EXPANDED_H = theme.SIDEBAR_MIN_EXPANDED_H
COMPACT_ALERT_HEIGHT = theme.COMPACT_ALERT_HEIGHT
TRACK_JUMP_DETECT_THRESHOLD = theme.TRACK_JUMP_DETECT_THRESHOLD
TRACK_JUMP_DETECT_LIMIT = theme.TRACK_JUMP_DETECT_LIMIT
RECENT_ROUTE_ITEM_HEIGHT = theme.RECENT_ROUTE_ITEM_HEIGHT
RECENT_ROUTE_CARD_PADDING = theme.RECENT_ROUTE_CARD_PADDING
TRACKED_ROUTE_CARD_PADDING = theme.TRACKED_ROUTE_CARD_PADDING

BG = theme.BG
BG_HOVER = theme.BG_HOVER
FG = theme.FG
FG_DIM = theme.FG_DIM
ACCENT = theme.ACCENT
ACCENT_SOFT = theme.ACCENT_SOFT
BORDER = theme.BORDER
DOT_LOCKED = theme.DOT_LOCKED
DOT_INERTIAL = theme.DOT_INERTIAL
DOT_LOST = theme.DOT_LOST
DOT_SEARCHING = theme.DOT_SEARCHING
RADIUS = theme.RADIUS
